---
- name: Install and configure MongoDB cluster
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    mongodb_replication: "{{ mongodb_replication | default(false) }}"
    mongodb_replication_members: "{{ mongodb_replication_members | default([]) }}"

  tasks:
    - name: Install MongoDB
      apt:
        name: mongodb
        state: present

    - name: Start MongoDB service
      service:
        name: mongodb
        state: started

    - name: Initiate MongoDB replication
      command: "mongo --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})\""
      when: mongodb_replication

    - name: Add MongoDB replication members
      command: mongo --eval 'rs.add("{{ item }}")'
      with_items: "{{ mongodb_replication_members }}"
      when: mongodb_replication and mongodb_replication_members is defined

# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"

# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"