---
- name: Install and configure MongoDB cluster
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    mongodb_replication: "{{ mongodb_replication | default(false) }}"
    mongodb_replication_members: "{{ mongodb_replication_members | default([]) }}"
    mongodb_version: "5.0"
    mongodb_dbpath: "/var/lib/mongodb"
    mongodb_journal_enabled: true
    mongodb_logpath: "/var/log/mongodb/mongod.log"
    mongodb_port: "27017"
    mongodb_authorization: enabled
  tasks:
    - name: Import the MongoDB public GPG Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Add the MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/{{ mongodb_version }} multiverse
        state: present
        update_cache: yes

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
            
    - name: Configure MongoDB
      template:
        src: mongod.conf.j2
        dest: /etc/mongod.conf
      notify: restart mongod

    - name: Initiate MongoDB replication
      command: "mongo --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})\""
      when: mongodb_replication

    - name: Add MongoDB replication members
      command: mongo --eval 'rs.add("{{ item }}")'
      with_items: "{{ mongodb_replication_members }}"
      when: mongodb_replication and mongodb_replication_members is defined

  handlers:
    - name: restart mongod
      service:
        name: mongod
        state: restarted
# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"

# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"