---
- name: Install and configure MongoDB cluster
  hosts: "{{ target_hosts }}"
  become: true
  vars:
    mongodb_replication: "{{ mongodb_replication | default(false) }}"
    mongodb_replication_members: "{{ mongodb_replication_members | default([]) }}"

  tasks:

    - name: Import the MongoDB public GPG Key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-5.0.asc
        state: present

    - name: Add the MongoDB repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse
        state: present
        update_cache: yes

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install MongoDB dependencies
      apt:
        pkg:
          - libc6
          - mongodb-org-server
          - mongodb-org-mongos
          - mongodb-org-shell
          - mongodb-org-tools 
          - mongodb-org-database
        state: latest
        update_cache: true

    - name: Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: Initiate MongoDB replication
      command: "mongo --eval \"rs.initiate({_id: 'rs0', members: [{_id: 0, host: 'localhost:27017'}]})\""
      when: mongodb_replication

    - name: Add MongoDB replication members
      command: mongo --eval 'rs.add("{{ item }}")'
      with_items: "{{ mongodb_replication_members }}"
      when: mongodb_replication and mongodb_replication_members is defined

# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"

# ansible-playbook playbook.yml -e "target_hosts='mongo_servers' mongodb_replication=true mongodb_replication_members='[\"mongo_server_2:27017\", \"mongo_server_3:27017\"]'"